/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_byc_testndk_TestJni */

#ifndef _Included_com_example_byc_testndk_TestJni
#define _Included_com_example_byc_testndk_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_byc_testndk_TestJni
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_byc_testndk_TestJni_getStringFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
